// vue/views/auth/components/Footer.vue
<template>
    <div class="text-center mt-4" v-if="hd.site">
        <a
            href="/wechat/login"
            class="no-underline hover:text-gray-900 text-blue-dark text-xs"
            v-if="hd.site.setting.wechatweb_login && (hd.device.wechat || hd.device.desktop)"
        >
            微信登录 ·
        </a>

        <router-link class="no-underline hover:text-gray-900 text-blue-dark text-xs" to="/register" v-if="$route.name != 'auth.register'">
            注册 ·
        </router-link>

        <router-link class="no-underline hover:text-gray-900 text-blue-dark text-xs" to="/login" v-if="$route.name != 'auth.login'">
            登录 ·
        </router-link>

        <router-link class="no-underline hover:text-gray-900 text-blue-dark text-xs" to="/forget">
            找回密码 ·
        </router-link>

        <a class="no-underline hover:text-gray-900 text-blue-dark text-xs" href="/">
            返回首页
        </a>
    </div>
</template>

<script>
export default {}
</script>

<style></style>

// packages/react/core/components/login/Footer.tsx
import { Button } from "@/components/ui/button"
import { FieldDescription } from "@/components/ui/field"
import { Link } from "@tanstack/react-router"

export const Footer = () => {
	return <div className="space-y-2">
		<Link to="/auth/wechat" className="w-full flex">
			<Button variant="outline" type="button" className="w-full" size={'lg'}>
				使用 微信 登录
			</Button>
		</Link>
		<FieldDescription className="text-center text-sm flex items-center justify-center gap-2">
			<Link to="/auth/login" className="hover:underline">登录</Link>
			<span className="text-muted-foreground">·</span>
			<Link to="/auth/register" className="hover:underline">注册</Link>
			<span className="text-muted-foreground">·</span>
			<Link to="/auth/forget" className="hover:underline">找回密码</Link>
		</FieldDescription>
	</div>
}
